services:
  chroma:
    image: chromadb/chroma:latest
    environment:
      ALLOW_RESET: TRUE
  llm-rag-go:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - chroma
    environment:
      CHROMA_URL: http://chroma:8000