FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd/initvectorstore/ ./cmd/initvectorstore/
COPY ./pkg/ ./pkg/

RUN go build -o initvectorstore ./cmd/initvectorstore/

FROM alpine:latest

COPY --from=builder /app/initvectorstore /bin/initvectorstore

EXPOSE 8080

CMD ["/bin/initvectorstore"]